name: 'Utility'
on:
  workflow_call:
    inputs:
      param_bool:
        type: boolean
        required: true
      macos-files:
        type: string
        description: 'Some macOS files to use'
      windows-files:
        type: string
        description: 'Some Windows files to use'
jobs:
  job1:
    name: 'Job 1'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "param_bool=${{ inputs.param_bool }}"
          echo "inputs.param_bool == true is ${{ inputs.param_bool == true }}"
          echo "inputs.param_bool == false is ${{ inputs.param_bool == false }}"
          echo "inputs.param_bool == 'true' is ${{ inputs.param_bool == 'true' }}"
          echo "inputs.param_bool == 'false' is ${{ inputs.param_bool == 'false' }}"
          echo "inputs.macos-files=${{ inputs.macos-files }}"
          echo "inputs.windows-files=${{ inputs.windows-files }}"
          if [! d test_output ]; then
            mkdir -p test_output
          fi
          cp -r ${{ inputs.macos-files }} test_output
          ls test_output
          SRC_FILES=()
          SRC_FILES+=("Release" "Debug" "output")
          SRC_FILES+=(${{ inputs.macos-files }})
          SRC_FILES+=("Release" "Debug" "include")
          echo "SRC_FILES=${SRC_FILES}"
          SRC_FILES=()
          SRC_FILES+=(Release Debug output)
          SRC_FILES+=(${{ inputs.windows-files }})
          SRC_FILES+=(Release Debug include)
          echo "SRC_FILES=${SRC_FILES}"
        shell: bash
